### PR TITLE
remove grunt-autoprefixer in favor of grunt-postcss with autoprefixer.

### PR DESCRIPTION
**Pull request by ctalkington**
grunt-autoprefixer was deprecated - https://github.com/nDmitry/grunt-autoprefixer/commit/e020f878d5fe1a3f9f15bc7533b31c12ffa74799

compass will likely need an update to call postcss instead of autoprefixer too.

cc @robneu

### CODE REVIEW

**Comment by robneu** [comment]
I need to check, but I don't think anything will need updated in Compass. Do you know if there's anything else in our current build that we can use PostCSS for?

**Comment by robneu** [comment]
I take that back, it looks like there's an autoprefixer call in the Compass aliases. I'll get that updated and merge this in. :+1:

**Comment by ctalkington** [comment]
not at this point but postcss is gaining traction so its likely there will be more tasks using it since it does in memory edits iirc

**Comment by ctalkington** [comment]
things like cssjanus could possibly be replaced in future.

https://github.com/MohammadYounes/rtlcss

core did this recently

https://core.trac.wordpress.org/changeset/31573

**Comment by robneu** [comment]
That looks promising. I've been holding off on a major update of Compass because HC 3.0 has been in development for quite a while now, but I think I'm going to need to do something soon. Using anything other than the Composer locked version of HC with Compass will totally break.

We've been going in another direction with themes internally, so things are a little weird at the moment. Hopefully I'll be able to get all this sorted out in the next month or so.

**Comment by ctalkington** [comment]
totally understand, i personally use an internally modded version of compass with genesis so I mostly only use the config handling and few other little jewels :)

**Comment by robneu** [comment]
Ah, makes sense. For the projects we're working on now and some upcoming free theme releases under the Site Care brand we've moved to a structure that's closer to Genesis because the plugin API makes it easier to modify output from add-on plugins and whatnot.

I'm not sure how many people are actively using Compass or in what way they're using it (modified, out of the box, bits and pieces, etc) so it's hard to judge how much of an impact large changes will have.

**Comment by ctalkington** [comment]
yah, i find more value in the grunt flow and accessibility js than the whole.

**Pull request merged**
